import pandas as pd
import pickle
import os
from scripts.model.train_and_save_model import split_and_scaled_data
from scripts.settings import *
from sklearn.metrics import median_absolute_error, mean_absolute_error, mean_absolute_percentage_error


def evaluate_model(y_test: pd.Series, y_pred: pd.Series) -> (float, float, float):
    """
    Evaluate the performance of a regression model by computing three different error metrics: Median Absolute Error (MedAE),
    Mean Absolute Error (MAE), and Mean Absolute Percentage Error (MAPE).
    :param y_test: pd.Series, the actual target values (ground truth) for the test dataset.
    :param y_pred: pd.Series, the predicted target values generated by a regression model.
    :return:Tuple(float, float, float): a tuple containing the following error metrics: MedAE, MAE, MAPE.
    """
    median_absolute_err = median_absolute_error(y_test, y_pred)
    mean_absolute_err = mean_absolute_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    return median_absolute_err, mean_absolute_err, mape


def main():
    # load the test dataset
    df_test = pd.read_csv('../prepare_data/df_test.csv')
    target = 'price'
    X_test, y_test = split_and_scaled_data(df_test, target)
    # load the trained models
    rf_regressor_opt = pickle.load(open(os.path.join(trained_model_dir, random_forest_file), 'rb'))
    xgb_opt = pickle.load(open(os.path.join(trained_model_dir, xgboost_file), 'rb'))
    knn = pickle.load(open(os.path.join(trained_model_dir, knn_file), 'rb'))
    # Predict the target on the test data
    y_pred = rf_regressor_opt.predict(X_test)
    y_pred_xgb = xgb_opt.predict(X_test)
    y_pred_knn = knn.predict(X_test)

    metrics_rf = evaluate_model(y_test, y_pred)
    metrics_xgb = evaluate_model(y_test, y_pred_xgb)
    metrics_knn = evaluate_model(y_test, y_pred_knn)

    #  Print metrics
    print("Random Forest=> Median Squared Error, Mean Absolute Error, Mean Absolute Percentage Error:", metrics_rf)
    print("XGBoost=> Median Squared Error, Mean Absolute Error, Mean Absolute Percentage Error:", metrics_xgb)
    print("KNN=> Median Squared Error, Mean Absolute Error, Mean Absolute Percentage Error:", metrics_knn)


if __name__ == '__main__':
    main()
